CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE audit_action_type AS ENUM (
    'CREATE', 'UPDATE', 'DELETE', 'VIEW', 'PUBLISH'
);

CREATE TYPE mark_status_type AS ENUM (
    'DRAFT', 'DELAYED', 'FLAGGED', 'PUBLISHED', 'ANOMALY'
);

CREATE TYPE user_role_type AS ENUM (
    'STUDENT', 'LECTURER', 'COORDINATOR', 'HOD', 'ADMIN'
);
